export enum USER_ROLE {
    STUDENT = "STUDENT",
    PARENT = "PARENT",
    OPS = "OPS",
    COUNSELOR = "COUNSELOR",
    ADMIN = "ADMIN",
    ALUMNI = "ALUMNI",
    SUPER_ADMIN = "SUPER_ADMIN",
    SERVICE_PROVIDER = "SERVICE_PROVIDER",
  }
  

